name: Terraform and Ansible CI/CD

concurrency:
  group: terraform-main
  cancel-in-progress: true

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./terraform/main
      TFVARS_FILE: terraform.dev.tfvars
      BACKEND_ENV_FILE: backend.hcl

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create tfvars file
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          cat <<EOF > ${{ env.TFVARS_FILE }}
          ${{ secrets.TERRAFORM_ENV }}
          EOF

          echo "===== Generated tfvars ====="
          cat ${{ env.TFVARS_FILE }}

      - name: Create backend env file
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          cat <<EOF > ${{ env.BACKEND_ENV_FILE }}
          ${{ secrets.TERRAFORM_BACKEND_HCL }}
          EOF

          echo "===== backend.hcl ====="
          cat ${{ env.BACKEND_ENV_FILE }}

      - name: Configure AWS Credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform init -backend-config=${{ env.BACKEND_ENV_FILE }}

      - name: Terraform Format
        working-directory: ${{ env.WORKING_DIRECTORY }}
        continue-on-error: true
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIRECTORY }}
        continue-on-error: true
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform plan -no-color -var-file=${{ env.TFVARS_FILE }} -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform apply -auto-approve tfplan

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-env
          path: ${{ env.WORKING_DIRECTORY }}/ansible-env.yml

  ansible:
    name: ansible
    runs-on: ubuntu-latest
    needs: terraform
    env:
      WORKING_DIRECTORY: ./ansible
      IPS_ENV_FILE: ansible-env.yml
      EXTRA_ENV_FILE: extra-env.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up ssh
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          echo "${{ secrets.AWS_PEM_FILE }}" > ${{ secrets.SSH_KEY_NAME }}
          chmod 600 ${{ secrets.SSH_KEY_NAME }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ansible-env
          path: ${{ env.WORKING_DIRECTORY }}

      - name: Create extra env file
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          cat <<EOF > ${{ env.EXTRA_ENV_FILE }}
          SSH_KEY_PATH: "${{ env.WORKING_DIRECTORY }}/${{ secrets.SSH_KEY_NAME }}"
          IMAGE_NAME: "${{ secrets.DOCKER_IMAGE_NAME }}"
          APP_PORT: "${{ vars.APP_PORT }}"
          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
          EOF

          echo "===== extra-env.yml ====="
          cat extra-env.yml
      
      - name: Install ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          ansible-playbook env-main.yml \
          --extra-vars "@${{ env.IPS_ENV_FILE }} \
          --extra-vars "@${{ env.EXTRA_ENV_FILE }}"