name: Terraform CI/CD

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./terraform/main
      TFVARS_FILE: terraform.auto.tfvars
      BACKEND_ENV_FILE: backend.hcl

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create tfvars file
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          echo "${{ secrets.TERRAFORM_ENV }}" > ${{ env.TFVARS_FILE }}
      
      - name: Create backend env file
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: | 
          echo "${{ env.TERRAFORM_BACKEND_HCL }}" > ${{ env.BACKEND_ENV_FILE }}

      - name: Configure AWS Credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform init -backend-config=${{ env.BACKEND_ENV_FILE }}

      - name: Terraform Format
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform plan -no-color -var-file=${{ env.TFVARS_FILE }} -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform apply -auto-approve tfplan