name: Deploy all modules

concurrency:
  group: terraform-main
  cancel-in-progress: true

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    name: Deploy myce backend
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./ansible
      IPS_ENV_FILE: dev-env.yml
      EXTRA_ENV_FILE: extra-env.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  

      - name: Download dev env file from s3
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          aws s3 cp s3://${{ vars.AWS_S3_ARTIFACT_BUCKET_NAME }}/${{ vars.AWS_S3_MYCE_ARTIFACT_PATH }} ./${{ env.IPS_ENV_FILE }}
   
      - name: Set up ssh
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          echo "${{ secrets.AWS_PEM_FILE }}" > ${{ secrets.SSH_KEY_NAME }}
          chmod 400 ${{ secrets.SSH_KEY_NAME }}

      - name: Create exra-env file
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          cat <<EOF > "${{ env.EXTRA_ENV_FILE }}"
          SSH_KEY_PATH: './${{ secrets.SSH_KEY_NAME }}'
          IMAGE_NAME: '${{ secrets.DOCKER_IMAGE_NAME }}'
          APP_PORT: '${{ vars.APP_PORT }}'
          DOCKER_USERNAME: '${{ vars.DOCKER_USERNAME }}'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
          EOF

          echo "===== ${{ env.EXTRA_ENV_FILE }} ====="
          cat "${{ env.EXTRA_ENV_FILE }}"

      - name: Install ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env: 
          SSH_KEY_PATH: ./${{ secrets.SSH_KEY_NAME }}
        run: |
          ansible-playbook deploy-main.yml \
          -i inventory.yml \
          --extra-vars "@${{ env.IPS_ENV_FILE }}" \
          --extra-vars "@${{ env.EXTRA_ENV_FILE }}"
      